apiVersion: v1
kind: Secret
metadata:
  name: agixt-secrets
  namespace: agixt
type: Opaque
data:
  AGIXT_API_KEY: "" # Base64 encoded value
  POSTGRES_PASSWORD: "" # Base64 encoded value
  AZURE_API_KEY: "" # Base64 encoded value
  GOOGLE_API_KEY: "" # Base64 encoded value
  OPENAI_API_KEY: "" # Base64 encoded value 