apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agixt-workspace
  namespace: agixt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agixt-models
  namespace: agixt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi 